language: node_js
node_js:
  - "0.8"
  - "0.10"
php:
  - 5.3
before_install:
  - npm install -g grunt-cli
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer